image:
  repository: grekodocker/partygames
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "50m"
    memory: "256Mi"

storage:
  mountPath: /data
  # storageClass: ""  # leave unset to use the cluster default StorageClass
  size: 1Gi

terminationGracePeriodSeconds: 2

ingress:
  enabled: true
  host: partygames.alexgr.space
  tls:
    secretName: partygames-alexgr-space-tls
